config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :micropost, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence:true, length: {maximum:140}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid Username / Password !'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success]="Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Ruby on Rails base Title'
    if page_title.empty?
      base_title
    else
     "#{base_title}|#{page_title}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    reset_session
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- component -->
<div class="bg-grey-lighter p-8">
    <div class="sm:flex mb-4">
  <div class="sm:w-1/4 h-auto">
      <div class="text-orange mb-2">Orange</div>
      <ul class="list-reset leading-normal">
          <li class="hover:text-orange text-grey-darker">One</li>
          <li class="hover:text-orange text-grey-darker">Two</li>
          <li class="hover:text-orange text-grey-darker">Three</li>
          <li class="hover:text-orange text-grey-darker">Four</li>
          <li class="hover:text-orange text-grey-darker">Five</li>
          <li class="hover:text-orange text-grey-darker">Six</li>
          <li class="hover:text-orange text-grey-darker">Seven</li>
          <li class="hover:text-orange text-grey-darker">Eight</li>
      </ul>
  </div>
  <div class="sm:w-1/4 h-auto sm:mt-0 mt-8">
      <div class="text-blue mb-2">Blue</div>
      <ul class="list-reset leading-normal">
          <li class="hover:text-blue text-grey-darker">One</li>
          <li class="hover:text-blue text-grey-darker">Two</li>
          <li class="hover:text-blue text-grey-darker">Three</li>
      </ul>

    <div class="text-blue-light mb-2 mt-4">Blue-light</div>
      <ul class="list-reset leading-normal">
          <li class="hover:text-blue-light text-grey-darker">One</li>
          <li class="hover:text-blue-light text-grey-darker">Two</li>
          <li class="hover:text-blue-light text-grey-darker">Three</li>
      </ul>

  </div>
  <div class="sm:w-1/4 h-auto sm:mt-0 mt-8">
            <div class="text-green-dark mb-2">Green-dark</div>
      <ul class="list-reset leading-normal">
          <li class="hover:text-green-dark text-grey-darker">One</li>
          <li class="hover:text-green-dark text-grey-darker">Two</li>
          <li class="hover:text-green-dark text-grey-darker">Three</li>
      </ul>

    <div class="text-green-light mb-2 mt-4">Green-light</div>
      <ul class="list-reset leading-normal">
          <li class="hover:text-green-light text-grey-darker">One</li>
          <li class="hover:text-green-light text-grey-darker">Two</li>
          <li class="hover:text-green-light text-grey-darker">Three</li>
      </ul>


  </div>
    <div class="sm:w-1/2 sm:mt-0 mt-8 h-auto">
        <div class="text-red-light mb-2">Newsletter</div>
        <p class="text-grey-darker leading-normal">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi, consectetur. </p>
        <div class="mt-4 flex">
            <input type="text" class="p-2 border border-grey-light round text-grey-dark text-sm h-auto" placeholder="Your email address">
            <button class="bg-orange text-white rounded-sm h-auto text-xs p-3">Subscribe</button>
        </div>
    </div>

</div>
</div>

app/views/layouts/_header.html.erb
<nav class="font-sans flex flex-col text-center sm:flex-row sm:text-left sm:justify-between py-4 px-6 bg-white shadow sm:items-baseline w-full">
  <div class="mb-2 sm:mb-0">
    <%= link_to "Home", root_path, class: "text-2xl no-underline text-grey-darkest hover:text-blue-dark" %>
  </div>
  <div>
    <%= link_to "Help", help_path	, class: "text-lg no-underline text-grey-darkest hover:text-blue-dark ml-2" %>
    <% if logged_in? %>
    <%= link_to "Logout", logout_path , method: :delete, class: "text-lg no-underline text-grey-darkest hover:text-blue-dark ml-2" %>
    <% else %>
      <%= link_to "Sign Up", signup_path, class: "text-lg no-underline text-grey-darkest hover:text-blue-dark ml-2" %>
      <%= link_to "Sign In", login_path	, class: "text-lg no-underline text-grey-darkest hover:text-blue-dark ml-2" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="min-h-screen">
  <%= render 'layouts/header'%>
  <div class="container flex">
    <%= yield %>
  </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<!-- <li id="micropost- <%=micropost.id%>">
  <span class="user"><%=link_to micropost.user.name, micropost.user%></span>
  <span class="content"><%=micropost.content%></span>
  <span class="timestamp">
    Posted <%=time_ago_in_words(micropost.created_at)%> ago.
  </span>
</li> -->

<div class="col-span-2 sm:col-span-4 xl:col-span-4">
  <h3 class="font-semibold text-black"><%=link_to micropost.user.name, micropost.user%></h3>
  <p>
    <%=micropost.content%>
  </p>
</div>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
<div class="bg-red-lightest border border-red-light text-red-dark pl-4 pr-8 py-3 rounded relative" role="alert">
  <strong class="font-bold">Brbrbr!</strong>
  <span class="block sm:inline">The form contains <%= pluralize(@user.errors.count, "error") %></span>
</div>
<%end%>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help">Rails Tutorial Help page</a>.
  To get help on this sample app, see the<a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="mt-10 m-auto">
  <h1 class="text-purple-700 text-3xl">Sample App</h1>
  <p>This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </p>
  <br/>
  <%= link_to "Sign Up Now !", signup_path, class: "border border-indigo-500 text-indigo-500 rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:text-white hover:bg-indigo-600 focus:outline-none focus:shadow-outline" %>
  <%= link_to "Sign In !", login_path, class: "border border-indigo-500 text-indigo-500 rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:text-white hover:bg-indigo-600 focus:outline-none focus:shadow-outline" %>
</div>

app/views/users/new.html.erb
<div class="bg-grey-lighter min-h-screen flex flex-col mx-auto">
  <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
    <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
      <%= render 'shared/error_message' %>
      <h1 class="mb-8 text-3xl text-center">Sign up</h1>
      <%= form_with(model: @user, local: true) do |u| %>
        <%= u.text_field :name, class: "block border border-grey-light w-full p-3 rounded mb-4", placeholder: 'Full Name' %>
        <%= u.email_field :email, class: "block border border-grey-light w-full p-3 rounded mb-4", placeholder: 'Email' %>
        <%= u.password_field :password, class: "block border border-grey-light w-full p-3 rounded mb-4", placeholder: 'Password' %>
        <%= u.password_field :password_confirmation, class: "block border border-grey-light w-full p-3 rounded mb-4", placeholder: 'Password Confirmation' %>
        <%= u.submit 'Create My Account', class: "w-full text-center py-3 rounded bg-green text-black hover:bg-green-dark focus:outline-none my-1 cursor-pointer" %>
          <div class="text-center text-sm text-grey-dark mt-4">
              By signing up, you agree to the
              <a class="no-underline border-b border-grey-dark text-grey-dark" href="#">
                  Terms of Service
              </a> and
              <a class="no-underline border-b border-grey-dark text-grey-dark" href="#">
                  Privacy Policy
              </a>
          </div>
      </div>
      <% end %>
      <div class="text-grey-dark mt-6">
          Already have an account?
          <a class="no-underline border-b border-blue text-blue" href="../login/">
              Log in
          </a>.
        </div>
      </div>
  </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="bg-white my-12 pb-6 w-full justify-center items-center overflow-hidden md:max-w-sm rounded-lg shadow-sm mx-auto">
  <div class="relative h-40">
    <img class="absolute h-full w-full object-cover" src="https://images.unsplash.com/photo-1448932133140-b4045783ed9e?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80">
  </div>
  <div class="relative shadow mx-auto h-24 w-24 -my-12 border-white rounded-full overflow-hidden border-4">
    <img class="object-cover w-full h-full" src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=200&q=80">
  </div>
  <div class="mt-16">
    <h1 class="text-lg text-center font-semibold">
      <%=@user.name %>
    </h1>
    <h1 class="text-lg text-center font-semibold">
      <%=@user.email %>
    </h1>
  </div>
  <h3 class="text-center">Microposts (<%= @user.microposts.count %>)</h3>
  <div class="flex flex-wrap mt-12 justify-center">
    <% if @user.microposts.any? %>
    <div class="grid grid-cols-1 sm:grid-cols-6 md:grid-cols-6 lg:grid-cols-6 xl:grid-cols-6 gap-4">
        <%= render @microposts %>
    </div>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>